List<Map<String, dynamic>> postsList = [
  {
    'profile_picture': 'assets/images/profile/profile1.jpg',
    'username': 'amgartendev',
    'date': '4 days ago',
    'image': 'assets/images/posts/image1.jpg',
    'description': 'Miami Beach giving that Bahamas vibe 🌴🌊',
    'liked_by': 'thiagok',
    'likes': 215,
    'comments': 25,
    'reposts': 2,
    'shares': 5,
  },
  {
    'profile_picture': 'assets/images/profile/profile1.jpg',
    'username': 'amgartendev',
    'date': '2 weeks ago',
    'image': 'assets/images/posts/image2.jpg',
    'description': "Finally where I'm meant to be... #Utah #BeehiveState",
    'liked_by': 'thiagok',
    'likes': 479,
    'comments': 31,
    'reposts': 7,
    'shares': 14,
  },
  {
    'profile_picture': 'assets/images/profile/profile2.jpg',
    'username': 'thiagok',
    'date': '1 month ago',
    'image': 'assets/images/posts/image3.jpg',
    'description': 'Woke up with this cinematic view of NYC today 🔥',
    'liked_by': 'amgartendev',
    'likes': 397,
    'comments': 17,
    'reposts': 3,
    'shares': 22,
  },
];
